In [350]:
from IPython.display import display,HTML
import numpy as np
import pandas as pd

class Student:
    
    def header(self, header,font=None):
        display(HTML(f"<h2 style='text-align:center;color:green;'>{header}</h2>"))

    def static(self, data):
        self.header("Load the Dataset",font=("times of roman",20,"bold"))
        display(data)
        self.header("Display the first 10 Rows",font=("times of roman",20,"bold"))
        display(data.head(10))
        self.header("Display the last 10 Rows",font=("times of roman",20,"bold"))
        display(data.tail(10))
        self.header("Find the number of rows and columns",font=("times of roman",20,"bold"))
        display(data.shape)
        self.header("Display all columns",font=("times of roman",20,"bold"))
        display(data.columns.to_list)
        self.header("Check the data types of every columns",font=("times of roman",20,"bold"))
        display(data.dtypes)
        self.header("Display the dataset summery",font=("times of roman",20,"bold"))
        display(data.info)
        self.header("Display Descriptive statistics",font=("times of roman",20,"bold"))
        display(data.describe)
        self.header("check the memory usage",font=("times of roman",20,"bold"))
        display(data.memory_usage)

    def exploring(self,data):
        self.header("Dataset contains missing values",font=("times of roman",20,"bold"))
        display(data.isnull().any()) 
        self.header("count missing values column-wise",font=("times of roman",20,"bold"))
        display(data.isnull().sum())
        self.header("Check duplicate rows",font=("times of roman",20,"bold"))
        display(data.duplicated().sum())
        self.header("Remove duplicate Rows",font=("times of roman",20,"bold"))
        display(data.drop_duplicates())
        self.header("Count unique values in every columns",font=("times of roman",20,"bold"))
        display(data.nunique())
        self.header("Display unique gender",font=("times of roman",20,"bold"))
        display(data['gender'].unique())
        self.header("Display unique parental education levels",font=("times of roman",20,"bold"))
        display(data['parental level of education'].unique())
        self.header("Display unique lunch",font=("times of roman",20,"bold"))
        display(data['lunch'].unique())
        self.header("Display unique test preparation categories",font=("times of roman",20,"bold"))
        display(data['test preparation course'].unique())
        self.header("Display the frequency of each gender",font=("times of roman",20,"bold"))
        display(data['gender'].value_counts())


    def selecting_data(self,data):
        self.header("Display the math score column",font=("times of roman",20,"bold"))
        display(data['math score'])
        self.header("Display the reading & writting score",font=("times of roman",20,"bold"))
        display(data[['reading score','writing score']])
        self.header("Display the first 20 Rows",font=("times of roman",20,"bold"))
        display(data[:20])
        self.header("Display the Rows 30-50",font=("times of roman",20,"bold"))
        display(data[30:51])
        self.header("Display the only categorical column",font=("times of roman",20,"bold"))
        display(data.select_dtypes(include='object').columns.to_list)
        self.header("Display the only numerical column",font=("times of roman",20,"bold"))
        display(data.select_dtypes(include='number').columns.to_list)
        self.header("Display the first five students math score ",font=("times of roman",20,"bold"))
        display(data['math score'][:5])
        self.header("Display the last five student's reading score",font=("times of roman",20,"bold"))
        display(data['reading score'][-5:])
        self.header("select column using .loc",font=("times of roman",20,"bold"))
        display(data.loc[0:5,'gender':'lunch'])
        self.header("select rows using .iloc",font=("times of roman",20,"bold"))
        display(data.iloc[0:5,0:3])


    def filtering(self,data):
        self.header("Students with math score above 90",font=("times of roman",20,"bold"))
        display(data[data['math score']>90])
        self.header("Students with reading score above 80",font=("times of roman",20,"bold"))
        display(data[data['reading score']>80])
        self.header("Students with writin score above 90",font=("times of roman",20,"bold"))
        display(data[data['writing score']>40])
        self.header("Female Students",font=("times of roman",20,"bold"))
        display(data[data['gender']=='female'])
        self.header("Male students",font=("times of roman",20,"bold"))
        display(data[data['gender']=='male'])
        self.header("Students who completed the test preparation course",font=("times of roman",20,"bold"))
        display(data[data['test preparation course']=='compeleted'])
        self.header("Students who received standard lunch",font=("times of roman",20,"bold"))
        display(data[data['lunch']=='standard'])
        self.header("Students whose parents have a bachelor's degree",font=("times of roman",20,"bold"))
        display(data[data['parental level of education']=="bachelor's degree"])
        self.header("Students with math score above 90 and reading score above 90",font=("times of roman",20,"bold"))
        display(data[(data['math score']>90) & (data['reading score']>90)])
        self.header("Student whose reading score is greater then writing score")
        display(data[data['reading score']>data['writing score']])
        

    def sorting(self,data):
        self.header("sort students by math score",font=("times of roman",20,"bold"))
        display(data.sort_values(by='math score'))
        self.header("sort by reading score in desc order",font=("times of roman",20,"Bold"))
        display(data.sort_values(by='reading score',ascending=False))
        self.header("sort by writing score",font=("times of roman",20,"Bold"))
        display(data.sort_values(by='writing score'))
        self.header("sort by gender and math score",font=("times of roman",20,"Bold"))
        display(data.sort_values(by=['gender','math score']))
        self.header("Display the top 10 students on math score",font=("times of roman",20,"Bold"))
        display(data.sort_values(by='math score',ascending=False).head(10))
    
    def create(self,data):
        self.header("Create a Total score column",font=("times of roman",20,"bold"))
        data['Total Score'] = data[['math score','reading score','writing score']].sum(axis=1)
        display(data)
        self.header("Create a Average score column",font=("times of roman",20,"bold"))
        data['Average'] = data[['math score','reading score','writing score']].mean(axis=1)
        display(data)
        self.header("Create a Result column",font=("times of roman",20,"bold"))
        data['Result'] = np.where(data['Average']>=40,"Pass","Fail")
        display(data)
        self.header("Create a Greade column",font=("times of roman",20,"bold"))
        data['Grade'] = data['Average'].map(lambda x : "A" if x>=90
                                                      else "B" if x>=80
                                                      else "C" if x>=70
                                                      else "D" if x>60
                                                      else "F"
                                            )
        display(data)
        self.header("create a performance columns",font=("times of roman",20,"bold"))
        data['Performance'] = data['Average'].map(lambda x : "Excellent" if x>=90
                                                            else "Good" if x>=75
                                                            else "Average" if x>=60
                                                            else "Poor"
                                                  )
        display(data)


    def statis(self,data):
        self.header("Mean math score",font=("times of roman",20,"bold"))
        display(data['math score'].mean())
        self.header("Median reading score",font=("times of roman",20,"bold"))
        display(data['reading score'].median())
        self.header("Standard deviation of writing score",font=("times of roman",20,"bold"))
        display(data['writing score'].std())
        self.header("Highest math score",font=("times of roman",20,"bold"))
        display(data['math score'].max())
        self.header("Lowest reading score",font=("times of roman",20,"bold"))
        display(data['reading score'].min())
        self.header("Range of writing score",font=("times of roman",20,"bold"))
        display(data['writing score'].max() - data['writing score'].min())
        self.header("Correlation between math and reading",font=("times of roman",20,"bold"))
        display(data['math score'].corr(data['reading score']))
        self.header("correlation among all numerical columns",font=("times of roman",20,"bold"))
        display(data.corr(numeric_only=True))
        self.header("Variance",font=("times of roman",20,"bold"))
        display(data['math score'].var())
        self.header("calculate the percentiles",font=("times of roman",20,"bold"))
        display("25th => ",data['math score'].quantile(0.25))
        display("50th => ",data['math score'].quantile(0.50))
        display("75th => ",data['math score'].quantile(0.75))


    def groupby(self,data):
        self.header("Average math score by gender",font=("times of roman",20,"bold"))
        display(data.groupby(by='gender')['math score'].mean())
        self.header("Average reading score by gender",font=("times of roman",20,"bold"))
        display(data.groupby(by='gender')['reading score'].mean())
        self.header("Average writing score by gender",font=("times of roman",20,"bold"))
        display(data.groupby(by='gender')['writing score'].mean())
        self.header("Average scores based on lunch type",font=("times of roman",20,"bold"))
        display(data.groupby(by='lunch')[['math score','reading score','writing score']].mean())
        self.header("Average scores based on parental education",font=("times of roman",20,"bold"))
        display(data.groupby(by='parental level of education')
                [['math score','reading score','writing score']].mean())
        self.header("Average scores based on preparation course",font=("times of roman",20,"bold"))
        display(data.groupby(by='test preparation course')
                [['math score','reading score','writing score']].mean())
        self.header("Count students in each race/ethnicity.",font=("times of roman",20,"bold"))
        display(data['race/ethnicity'].value_counts())
        self.header("Highest math score in every race",font=("times of roman",20,"bold"))
        display(data.groupby(by='race/ethnicity')['math score'].max())
        self.header("Lowest reading score by gender",font=("times of roman",20,"bold"))
        display(data.groupby(by='gender')['reading score'].min())
        self.header("count students by parental education",font=("times of roman",20,"bold"))
        display(data['parental level of education'].value_counts())
        

    def value_count(self,data):
        self.header("count each gender",font=("times of roman",20,"bold"))
        display(data['gender'].value_counts())
        self.header("count lunch categories",font=("times of roman",20,"bold"))
        display(data['lunch'].value_counts())
        self.header("count test preparation categories",font=("times of roman",20,"bold"))
        display(data['test preparation course'].value_counts())
        self.header("count parental education levels",font=("times of roman",20,"bold"))
        display(data['parental level of education'].value_counts())
        self.header("count race/ethnicity groups",font=("times of roman",20,"bold"))
        print(data['race/ethnicity'].value_counts())


    def real_world(self,data):
        pass

    def bounus_challenge(self,data):
        self.header("score above 90 in all three subjects",font=("times of roman",20,"bold"))
        display(data[(data['math score']>90) & 
                     (data['reading score']>90) & 
                     (data['writing score']>90)])
        self.header("scored below 40 in all three subject",font=("times of roman",20,"bold"))
        display(data[(data['math score']<40) &
                     (data['reading score']<40) &
                     (data['writing score']<40)])
        self.header("Percentage of students who completed the test preparation course"
                    ,font=("times of roman",20,"bold"))
        display(((data['test preparation course']
                    [data['test preparation course']=='completed'].count())
                    /data.shape[0])*100)
        self.header("Highest-performing race/ethinicity group based on average total score",
                    font=("times of roman",20,"bold"))
        new = data['race/ethnicity'].value_counts()
        new = new[new > new.mean()]
        display(new[new == new.max()])
        self.header("which subject [Math,Reading,Writing ] has the highest average score",
                    font=("times of roman",20,"bold"))
        h_avg = data[['math score','reading score','writing score']].mean()
        display(h_avg[h_avg == h_avg.max()])
        self.header("Whose Reading score is at least 20 marks higher then their math score",
                    font=("times of roman",20,"bold"))
        display(data[data['reading score'] > data['math score']+20])
        self.header("Create Merit List sorted by total score",
                    font=("times of roman",20,"bold"))
        Merit_List = data.sort_values(by='Total Score',ascending=False)
        display(Merit_List)
        self.header("Identify the top 5 students in each subject",
                    font=("times of roman",20,"bold"))
        display(data.sort_values(by=['math score','reading score','writing score']
                                 ,ascending=False).iloc[:5])
        self.header("Export the final processed dataset",font=("times of roman",20,"bold"))
        display(data.to_csv("students_performance_cleaned.csv",index=False))
        
        
        



    

data = pd.read_csv("StudentsPerformance.csv")   # Dataset
obj = Student()

# Part 1 : Loading and Understanding Data

In [351]:
obj.static(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

(1000, 8)

<bound method IndexOpsMixin.tolist of Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')>

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

<bound method DataFrame.info of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

<bound method NDFrame.describe of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

<bound method DataFrame.memory_usage of      gender race/ethnicity parental level of education         lunch  \
0    female        group B           bachelor's degree      standard
1    female        group C                some college      standard
2    female        group B             master's degree      standard
3      male        group A          associate's degree  free/reduced
4      male        group C                some college      standard
..      ...            ...                         ...           ...
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
0                      none          72             72             74
1                 completed          69             90             88
2                      none          90             95             93
3                      none          47             57             44
4                      none          76             78             75
..                      ...         ...            ...            ...
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86

[1000 rows x 8 columns]>

# Part 2 : Exploring Data

In [352]:
obj.exploring(data)

gender                         False
race/ethnicity                 False
parental level of education    False
lunch                          False
test preparation course        False
math score                     False
reading score                  False
writing score                  False
dtype: bool

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

0

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

gender                          2
race/ethnicity                  5
parental level of education     6
lunch                           2
test preparation course         2
math score                     81
reading score                  72
writing score                  77
dtype: int64

array(['female', 'male'], dtype=object)

array(["bachelor's degree", 'some college', "master's degree",
       "associate's degree", 'high school', 'some high school'],
      dtype=object)

array(['standard', 'free/reduced'], dtype=object)

array(['none', 'completed'], dtype=object)

gender
female    518
male      482
Name: count, dtype: int64

# Part 3 : Selecting data

In [353]:
obj.selecting_data(data)

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

     reading score  writing score
0               72             74
1               90             88
2               95             93
3               57             44
4               78             75
..             ...            ...
995             99             95
996             55             55
997             71             65
998             78             77
999             86             86

[1000 rows x 2 columns]

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50
10,male,group C,associate's degree,standard,none,58,54,52
11,male,group D,associate's degree,standard,none,40,52,43
12,female,group B,high school,standard,none,65,81,73
13,male,group A,some college,standard,completed,78,72,70
14,female,group A,master's degree,standard,none,50,53,58
15,female,group C,some high school,standard,none,69,75,78
16,male,group C,high school,standard,none,88,89,86
17,female,group B,some high school,free/reduced,none,18,32,28
18,male,group C,master's degree,free/reduced,completed,46,42,46
19,female,group C,associate's degree,free/reduced,none,54,58,61

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
30,female,group D,some college,standard,none,69,74,74
31,female,group B,some college,standard,none,63,65,61
32,female,group E,master's degree,free/reduced,none,56,72,65
33,male,group D,some college,standard,none,40,42,38
34,male,group E,some college,standard,none,97,87,82
35,male,group E,associate's degree,standard,completed,81,81,79
36,female,group D,associate's degree,standard,none,74,81,83
37,female,group D,some high school,free/reduced,none,50,64,59
38,female,group D,associate's degree,free/reduced,completed,75,90,88
39,male,group B,associate's degree,free/reduced,none,57,56,57
40,male,group C,associate's degree,free/reduced,none,55,61,54
41,female,group C,associate's degree,standard,none,58,73,68
42,female,group B,associate's degree,standard,none,53,58,65
43,male,group B,some college,free/reduced,completed,59,65,66
44,female,group E,associate's degree,free/reduced,none,50,56,54
45,male,group B,associate's degree,standard,none,65,54,57
46,female,group A,associate's degree,standard,completed,55,65,62
47,female,group C,high school,standard,none,66,71,76
48,female,group D,associate's degree,free/reduced,completed,57,74,76
49,male,group C,high school,standard,completed,82,84,82
50,male,group E,some college,standard,none,53,55,48

<bound method IndexOpsMixin.tolist of Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='object')>

0    72
1    69
2    90
3    47
4    76
Name: math score, dtype: int64

995    99
996    55
997    71
998    78
999    86
Name: reading score, dtype: int64

   gender race/ethnicity parental level of education         lunch
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard
5  female        group B          associate's degree      standard

   gender race/ethnicity parental level of education
0  female        group B           bachelor's degree
1  female        group C                some college
2  female        group B             master's degree
3    male        group A          associate's degree
4    male        group C                some college

# Part 4 : Filtering

In [354]:
obj.filtering(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
34,male,group E,some college,standard,none,97,87,82
104,male,group C,some college,standard,completed,98,86,90
114,female,group E,bachelor's degree,standard,completed,99,100,100
121,male,group B,associate's degree,standard,completed,91,89,92
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
171,male,group E,some high school,standard,none,94,88,78
179,female,group D,some high school,standard,completed,97,100,100
233,male,group E,some high school,standard,none,92,87,78
263,female,group E,high school,standard,none,99,93,90
286,male,group E,associate's degree,standard,completed,97,82,88
306,male,group E,some college,standard,completed,99,87,81
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
469,male,group C,some college,standard,none,91,74,76
501,female,group B,associate's degree,standard,completed,94,87,92
503,female,group E,associate's degree,standard,completed,95,89,92
521,female,group C,associate's degree,standard,none,91,86,84
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
562,male,group C,bachelor's degree,standard,completed,96,90,92
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
571,male,group A,bachelor's degree,standard,none,91,96,92
594,female,group C,bachelor's degree,standard,completed,92,100,99
612,male,group C,bachelor's degree,standard,completed,94,90,91
618,male,group D,master's degree,standard,none,95,81,84
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
685,female,group E,master's degree,standard,completed,94,99,100
689,male,group E,some college,free/reduced,none,93,90,83
710,male,group C,some college,standard,completed,93,84,90
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
719,male,group E,associate's degree,free/reduced,completed,91,73,80
736,male,group C,associate's degree,standard,none,92,79,84
779,male,group E,associate's degree,standard,completed,94,85,82
784,male,group C,bachelor's degree,standard,completed,91,81,79
815,male,group B,some high school,standard,completed,94,86,87
846,male,group C,master's degree,standard,completed,91,85,85
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
919,male,group B,some college,standard,completed,91,96,91
934,male,group C,associate's degree,standard,completed,98,87,90
950,male,group E,high school,standard,none,94,73,71
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
979,female,group C,associate's degree,standard,none,91,95,94

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
12,female,group B,high school,standard,none,65,81,73
...,...,...,...,...,...,...,...,...
989,female,group D,some college,free/reduced,completed,67,86,83
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
995,female,group E,master's degree,standard,completed,88,99,95
999,female,group D,some college,free/reduced,none,77,86,86

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
...,...,...,...,...,...,...,...,...
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
10,male,group C,associate's degree,standard,none,58,54,52
...,...,...,...,...,...,...,...,...
985,male,group A,high school,standard,none,57,51,54
987,male,group E,some high school,standard,completed,81,75,76
990,male,group E,high school,free/reduced,completed,86,81,75
994,male,group A,high school,standard,none,63,63,62
996,male,group C,high school,free/reduced,none,62,55,55

Empty DataFrame
Columns: [gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score]
Index: []

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
987,male,group E,some high school,standard,completed,81,75,76
991,female,group B,some high school,standard,completed,65,82,78
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
998,female,group D,some college,standard,completed,68,78,77

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
24,male,group D,bachelor's degree,free/reduced,completed,74,71,80
27,female,group C,bachelor's degree,standard,none,67,69,75
60,male,group E,bachelor's degree,free/reduced,completed,79,74,72
77,male,group A,bachelor's degree,standard,completed,80,78,81
...,...,...,...,...,...,...,...,...
916,male,group E,bachelor's degree,standard,completed,100,100,100
933,male,group C,bachelor's degree,free/reduced,completed,70,75,74
969,female,group B,bachelor's degree,standard,none,75,84,80
970,female,group D,bachelor's degree,standard,none,89,100,100
993,female,group D,bachelor's degree,free/reduced,none,62,72,74

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
114,female,group E,bachelor's degree,standard,completed,99,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
165,female,group C,bachelor's degree,standard,completed,96,100,100
179,female,group D,some high school,standard,completed,97,100,100
263,female,group E,high school,standard,none,99,93,90
451,female,group E,some college,standard,none,100,92,97
458,female,group E,bachelor's degree,standard,none,100,100,100
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
571,male,group A,bachelor's degree,standard,none,91,96,92
594,female,group C,bachelor's degree,standard,completed,92,100,99
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
685,female,group E,master's degree,standard,completed,94,99,100
712,female,group D,some college,standard,none,98,100,99
717,female,group C,associate's degree,standard,completed,96,96,99
855,female,group B,bachelor's degree,standard,none,97,97,96
864,male,group C,associate's degree,standard,none,97,93,91
886,female,group E,associate's degree,standard,completed,93,100,95
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
919,male,group B,some college,standard,completed,91,96,91
957,female,group D,master's degree,standard,none,92,100,100
962,female,group E,associate's degree,standard,none,100,100,100
979,female,group C,associate's degree,standard,none,91,95,94

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
...,...,...,...,...,...,...,...,...
991,female,group B,some high school,standard,completed,65,82,78
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77

# Part 5 : Sorting

In [355]:
obj.sorting(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
625,male,group D,some college,standard,completed,100,97,99
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
962,female,group E,associate's degree,standard,none,100,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
546,female,group A,some high school,standard,completed,92,100,97
970,female,group D,bachelor's degree,standard,none,89,100,100
149,male,group E,associate's degree,free/reduced,completed,100,100,93
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100
712,female,group D,some college,standard,none,98,100,99
...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30,26,22
980,female,group B,high school,free/reduced,none,8,24,23
596,male,group B,high school,free/reduced,none,30,24,15
327,male,group A,some college,free/reduced,none,28,23,19
59,female,group C,some high school,free/reduced,none,0,17,10

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
596,male,group B,high school,free/reduced,none,30,24,15
327,male,group A,some college,free/reduced,none,28,23,19
76,male,group E,some high school,standard,none,30,26,22
980,female,group B,high school,free/reduced,none,8,24,23
...,...,...,...,...,...,...,...,...
970,female,group D,bachelor's degree,standard,none,89,100,100
106,female,group D,master's degree,standard,none,87,100,100
957,female,group D,master's degree,standard,none,92,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
114,female,group E,bachelor's degree,standard,completed,99,100,100

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
59,female,group C,some high school,free/reduced,none,0,17,10
980,female,group B,high school,free/reduced,none,8,24,23
17,female,group B,some high school,free/reduced,none,18,32,28
787,female,group B,some college,standard,none,19,38,32
145,female,group C,some college,free/reduced,none,22,39,33
...,...,...,...,...,...,...,...,...
306,male,group E,some college,standard,completed,99,87,81
149,male,group E,associate's degree,free/reduced,completed,100,100,93
623,male,group A,some college,standard,completed,100,96,86
625,male,group D,some college,standard,completed,100,97,99
916,male,group E,bachelor's degree,standard,completed,100,100,100

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99
458,female,group E,bachelor's degree,standard,none,100,100,100
623,male,group A,some college,standard,completed,100,96,86
451,female,group E,some college,standard,none,100,92,97
149,male,group E,associate's degree,free/reduced,completed,100,100,93
916,male,group E,bachelor's degree,standard,completed,100,100,100
263,female,group E,high school,standard,none,99,93,90
306,male,group E,some college,standard,completed,99,87,81
114,female,group E,bachelor's degree,standard,completed,99,100,100

# Part 6 : Creating new columns

In [356]:
obj.create(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score
0,female,group B,bachelor's degree,standard,none,72,72,74,218
1,female,group C,some college,standard,completed,69,90,88,247
2,female,group B,master's degree,standard,none,90,95,93,278
3,male,group A,associate's degree,free/reduced,none,47,57,44,148
4,male,group C,some college,standard,none,76,78,75,229
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282
996,male,group C,high school,free/reduced,none,62,55,55,172
997,female,group C,high school,free/reduced,completed,59,71,65,195
998,female,group D,some college,standard,completed,68,78,77,223
999,female,group D,some college,free/reduced,none,77,86,86,249

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667
1,female,group C,some college,standard,completed,69,90,88,247,82.333333
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333
4,male,group C,some college,standard,none,76,78,75,229,76.333333
...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000
998,female,group D,some college,standard,completed,68,78,77,223,74.333333
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667,Pass
1,female,group C,some college,standard,completed,69,90,88,247,82.333333,Pass
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667,Pass
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333,Pass
4,male,group C,some college,standard,none,76,78,75,229,76.333333,Pass
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000,Pass
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333,Pass
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000,Pass
998,female,group D,some college,standard,completed,68,78,77,223,74.333333,Pass
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000,Pass

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result,Grade
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667,Pass,C
1,female,group C,some college,standard,completed,69,90,88,247,82.333333,Pass,B
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667,Pass,A
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333,Pass,F
4,male,group C,some college,standard,none,76,78,75,229,76.333333,Pass,C
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000,Pass,A
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333,Pass,F
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000,Pass,D
998,female,group D,some college,standard,completed,68,78,77,223,74.333333,Pass,C
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000,Pass,B

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result,Grade,Performance
0,female,group B,bachelor's degree,standard,none,72,72,74,218,72.666667,Pass,C,Average
1,female,group C,some college,standard,completed,69,90,88,247,82.333333,Pass,B,Good
2,female,group B,master's degree,standard,none,90,95,93,278,92.666667,Pass,A,Excellent
3,male,group A,associate's degree,free/reduced,none,47,57,44,148,49.333333,Pass,F,Poor
4,male,group C,some college,standard,none,76,78,75,229,76.333333,Pass,C,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,282,94.000000,Pass,A,Excellent
996,male,group C,high school,free/reduced,none,62,55,55,172,57.333333,Pass,F,Poor
997,female,group C,high school,free/reduced,completed,59,71,65,195,65.000000,Pass,D,Average
998,female,group D,some college,standard,completed,68,78,77,223,74.333333,Pass,C,Average
999,female,group D,some college,free/reduced,none,77,86,86,249,83.000000,Pass,B,Good

# Part 7 : Statistics

In [357]:
obj.statis(data)

66.089

70.0

15.195657010869642

100

17

90

0.8175796636720539

               math score  reading score  writing score  Total Score   Average
math score       1.000000       0.817580       0.802642     0.918746  0.918746
reading score    0.817580       1.000000       0.954598     0.970331  0.970331
writing score    0.802642       0.954598       1.000000     0.965667  0.965667
Total Score      0.918746       0.970331       0.965667     1.000000  1.000000
Average          0.918746       0.970331       0.965667     1.000000  1.000000

229.91899799799847

'25th => '

57.0

'50th => '

66.0

'75th => '

77.0

# Part 8 : Groupby

In [358]:

obj.groupby(data)

gender
female    63.633205
male      68.728216
Name: math score, dtype: float64

gender
female    72.608108
male      65.473029
Name: reading score, dtype: float64

gender
female    72.467181
male      63.311203
Name: writing score, dtype: float64

              math score  reading score  writing score
lunch
free/reduced   58.921127      64.653521      63.022535
standard       70.034109      71.654264      70.823256

                             math score  reading score  writing score
parental level of education
associate's degree            67.882883      70.927928      69.896396
bachelor's degree             69.389831      73.000000      73.381356
high school                   62.137755      64.704082      62.448980
master's degree               69.745763      75.372881      75.677966
some college                  67.128319      69.460177      68.840708
some high school              63.497207      66.938547      64.888268

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

race/ethnicity
group A    100
group B     97
group C     98
group D    100
group E    100
Name: math score, dtype: int64

gender
female    17
male      23
Name: reading score, dtype: int64

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

# Part 9 : Value Counts

In [359]:
obj.value_count(data)

gender
female    518
male      482
Name: count, dtype: int64

lunch
standard        645
free/reduced    355
Name: count, dtype: int64

test preparation course
none         642
completed    358
Name: count, dtype: int64

parental level of education
some college          226
associate's degree    222
high school           196
some high school      179
bachelor's degree     118
master's degree        59
Name: count, dtype: int64

race/ethnicity
group C    319
group D    262
group B    190
group E    140
group A     89
Name: count, dtype: int64

# Bonus Challenge(Optional)

In [360]:
obj.bounus_challenge(data)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result,Grade,Performance
114,female,group E,bachelor's degree,standard,completed,99,100,100,299,99.666667,Pass,A,Excellent
149,male,group E,associate's degree,free/reduced,completed,100,100,93,293,97.666667,Pass,A,Excellent
165,female,group C,bachelor's degree,standard,completed,96,100,100,296,98.666667,Pass,A,Excellent
179,female,group D,some high school,standard,completed,97,100,100,297,99.000000,Pass,A,Excellent
451,female,group E,some college,standard,none,100,92,97,289,96.333333,Pass,A,Excellent
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000,Pass,A,Excellent
546,female,group A,some high school,standard,completed,92,100,97,289,96.333333,Pass,A,Excellent
566,female,group E,bachelor's degree,free/reduced,completed,92,100,100,292,97.333333,Pass,A,Excellent
571,male,group A,bachelor's degree,standard,none,91,96,92,279,93.000000,Pass,A,Excellent
594,female,group C,bachelor's degree,standard,completed,92,100,99,291,97.000000,Pass,A,Excellent
625,male,group D,some college,standard,completed,100,97,99,296,98.666667,Pass,A,Excellent
685,female,group E,master's degree,standard,completed,94,99,100,293,97.666667,Pass,A,Excellent
712,female,group D,some college,standard,none,98,100,99,297,99.000000,Pass,A,Excellent
717,female,group C,associate's degree,standard,completed,96,96,99,291,97.000000,Pass,A,Excellent
855,female,group B,bachelor's degree,standard,none,97,97,96,290,96.666667,Pass,A,Excellent
864,male,group C,associate's degree,standard,none,97,93,91,281,93.666667,Pass,A,Excellent
886,female,group E,associate's degree,standard,completed,93,100,95,288,96.000000,Pass,A,Excellent
903,female,group D,bachelor's degree,free/reduced,completed,93,100,100,293,97.666667,Pass,A,Excellent
916,male,group E,bachelor's degree,standard,completed,100,100,100,300,100.000000,Pass,A,Excellent
919,male,group B,some college,standard,completed,91,96,91,278,92.666667,Pass,A,Excellent
957,female,group D,master's degree,standard,none,92,100,100,292,97.333333,Pass,A,Excellent
962,female,group E,associate's degree,standard,none,100,100,100,300,100.000000,Pass,A,Excellent
979,female,group C,associate's degree,standard,none,91,95,94,280,93.333333,Pass,A,Excellent

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result,Grade,Performance
17,female,group B,some high school,free/reduced,none,18,32,28,78,26.000000,Fail,F,Poor
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000,Fail,F,Poor
61,male,group A,some high school,free/reduced,none,39,39,34,112,37.333333,Fail,F,Poor
76,male,group E,some high school,standard,none,30,26,22,78,26.000000,Fail,F,Poor
91,male,group C,high school,free/reduced,none,27,34,36,97,32.333333,Fail,F,Poor
145,female,group C,some college,free/reduced,none,22,39,33,94,31.333333,Fail,F,Poor
211,male,group C,some college,free/reduced,none,35,28,27,90,30.000000,Fail,F,Poor
327,male,group A,some college,free/reduced,none,28,23,19,70,23.333333,Fail,F,Poor
338,female,group B,some high school,free/reduced,none,24,38,27,89,29.666667,Fail,F,Poor
363,female,group D,some high school,free/reduced,none,27,34,32,93,31.000000,Fail,F,Poor
466,female,group D,associate's degree,free/reduced,none,26,31,38,95,31.666667,Fail,F,Poor
555,female,group C,some college,free/reduced,none,32,39,33,104,34.666667,Fail,F,Poor
596,male,group B,high school,free/reduced,none,30,24,15,69,23.000000,Fail,F,Poor
601,female,group C,high school,standard,none,29,29,30,88,29.333333,Fail,F,Poor
787,female,group B,some college,standard,none,19,38,32,89,29.666667,Fail,F,Poor
895,female,group E,some high school,free/reduced,none,32,34,38,104,34.666667,Fail,F,Poor
896,male,group B,high school,free/reduced,none,36,29,27,92,30.666667,Fail,F,Poor
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333,Fail,F,Poor

35.8

race/ethnicity
group C    319
Name: count, dtype: int64

reading score    69.169
dtype: float64

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result,Grade,Performance
1,female,group C,some college,standard,completed,69,90,88,247,82.333333,Pass,B,Good
9,female,group B,high school,free/reduced,none,38,60,50,148,49.333333,Pass,F,Poor
69,female,group C,associate's degree,standard,none,39,64,57,160,53.333333,Pass,F,Poor
108,female,group B,associate's degree,free/reduced,none,52,76,70,198,66.000000,Pass,D,Average
158,female,group B,associate's degree,standard,completed,61,86,87,234,78.000000,Pass,C,Good
278,female,group C,some high school,free/reduced,none,65,86,80,231,77.000000,Pass,C,Good
287,female,group B,some high school,standard,none,67,89,82,238,79.333333,Pass,C,Good
357,female,group C,some college,free/reduced,completed,42,66,69,177,59.000000,Pass,F,Poor
371,female,group C,some college,free/reduced,completed,45,73,70,188,62.666667,Pass,D,Average
387,female,group C,associate's degree,free/reduced,none,57,78,67,202,67.333333,Pass,D,Average
414,female,group C,bachelor's degree,free/reduced,completed,51,72,79,202,67.333333,Pass,D,Average
423,female,group A,some high school,standard,completed,59,85,80,224,74.666667,Pass,C,Average
450,female,group C,some college,free/reduced,completed,64,85,85,234,78.000000,Pass,C,Good
595,female,group C,bachelor's degree,standard,completed,56,79,72,207,69.000000,Pass,D,Average
620,female,group C,high school,free/reduced,none,35,61,54,150,50.000000,Pass,F,Poor
698,female,group D,associate's degree,standard,completed,57,78,79,214,71.333333,Pass,C,Average
842,female,group B,high school,free/reduced,completed,23,44,36,103,34.333333,Fail,F,Poor
844,female,group D,some high school,free/reduced,completed,40,65,64,169,56.333333,Pass,F,Poor
992,female,group D,associate's degree,free/reduced,none,55,76,76,207,69.000000,Pass,D,Average

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result,Grade,Performance
916,male,group E,bachelor's degree,standard,completed,100,100,100,300,100.000000,Pass,A,Excellent
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000,Pass,A,Excellent
962,female,group E,associate's degree,standard,none,100,100,100,300,100.000000,Pass,A,Excellent
114,female,group E,bachelor's degree,standard,completed,99,100,100,299,99.666667,Pass,A,Excellent
179,female,group D,some high school,standard,completed,97,100,100,297,99.000000,Pass,A,Excellent
...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,male,group E,some high school,standard,none,30,26,22,78,26.000000,Fail,F,Poor
327,male,group A,some college,free/reduced,none,28,23,19,70,23.333333,Fail,F,Poor
596,male,group B,high school,free/reduced,none,30,24,15,69,23.000000,Fail,F,Poor
980,female,group B,high school,free/reduced,none,8,24,23,55,18.333333,Fail,F,Poor
59,female,group C,some high school,free/reduced,none,0,17,10,27,9.000000,Fail,F,Poor

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,Total Score,Average,Result,Grade,Performance
458,female,group E,bachelor's degree,standard,none,100,100,100,300,100.000000,Pass,A,Excellent
916,male,group E,bachelor's degree,standard,completed,100,100,100,300,100.000000,Pass,A,Excellent
962,female,group E,associate's degree,standard,none,100,100,100,300,100.000000,Pass,A,Excellent
149,male,group E,associate's degree,free/reduced,completed,100,100,93,293,97.666667,Pass,A,Excellent
625,male,group D,some college,standard,completed,100,97,99,296,98.666667,Pass,A,Excellent

None