In [1]:
import numpy as np
import pandas as pd

# series
series is a one dimensional data in which the indices
are also show

In [2]:
s = pd.Series([1,2,3,4])
s

0    1
1    2
2    3
3    4
dtype: int64

# Data frame
1. A dataframe is a data type present in pandas in which the data is stored into the form of row and columns 
2. syntax :-  pd.dataframe(dictinary)

In [3]:
# using dictionary
pd.DataFrame({
    'A':[1,2,3,4],
    'B':[10,20,30,40]
})

   A   B
0  1  10
1  2  20
2  3  30
3  4  40

In [4]:
# using list
pd.DataFrame(
    [
        ['Aman',10],
        ['Naman',20],
        ['Vikas',30]
    ],
    columns=['Name','Marks']
)

    Name  Marks
0   Aman     10
1  Naman     20
2  Vikas     30

In [5]:
df = pd.read_csv("CarPrice.csv")
df

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4
...,...,...,...,...,...,...,...,...,...,...
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1

In [6]:
df.head()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase
0,1,3,alfa-romero giulia,gas,std,two,convertible,rwd,front,88.6
1,2,3,alfa-romero stelvio,gas,std,two,convertible,rwd,front,88.6
2,3,1,alfa-romero Quadrifoglio,gas,std,two,hatchback,rwd,front,94.5
3,4,2,audi 100 ls,gas,std,four,sedan,fwd,front,99.8
4,5,2,audi 100ls,gas,std,four,sedan,4wd,front,99.4

In [7]:
df.tail()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase
200,201,-1,volvo 145e (sw),gas,std,four,sedan,rwd,front,109.1
201,202,-1,volvo 144ea,gas,turbo,four,sedan,rwd,front,109.1
202,203,-1,volvo 244dl,gas,std,four,sedan,rwd,front,109.1
203,204,-1,volvo 246,diesel,turbo,four,sedan,rwd,front,109.1
204,205,-1,volvo 264gl,gas,turbo,four,sedan,rwd,front,109.1

In [8]:
df.sample()

,car_ID,symboling,CarName,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase
187,188,2,volkswagen super beetle,diesel,turbo,four,sedan,fwd,front,97.3

In [9]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   car_ID          205 non-null    int64
 1   symboling       205 non-null    int64
 2   CarName         205 non-null    object
 3   fueltype        205 non-null    object
 4   aspiration      205 non-null    object
 5   doornumber      205 non-null    object
 6   carbody         205 non-null    object
 7   drivewheel      205 non-null    object
 8   enginelocation  205 non-null    object
 9   wheelbase       205 non-null    float64
dtypes: float64(1), int64(2), object(7)
memory usage: 16.1+ KB

In [10]:
df.describe()

           car_ID   symboling   wheelbase
count  205.000000  205.000000  205.000000
mean   103.000000    0.834146   98.756585
std     59.322565    1.245307    6.021776
min      1.000000   -2.000000   86.600000
25%     52.000000    0.000000   94.500000
50%    103.000000    1.000000   97.000000
75%    154.000000    2.000000  102.400000
max    205.000000    3.000000  120.900000

In [11]:
df.columns

Index(['car_ID', 'symboling', 'CarName', 'fueltype', 'aspiration',
       'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'wheelbase'],
      dtype='object')

In [12]:
# single columns
df['car_ID']

0        1
1        2
2        3
3        4
4        5
      ...
200    201
201    202
202    203
203    204
204    205
Name: car_ID, Length: 205, dtype: int64

In [13]:
# multiple columns
df[['car_ID', 'symboling', 'CarName']]

     car_ID  symboling                   CarName
0         1          3        alfa-romero giulia
1         2          3       alfa-romero stelvio
2         3          1  alfa-romero Quadrifoglio
3         4          2               audi 100 ls
4         5          2                audi 100ls
..      ...        ...                       ...
200     201         -1           volvo 145e (sw)
201     202         -1               volvo 144ea
202     203         -1               volvo 244dl
203     204         -1                 volvo 246
204     205         -1               volvo 264gl

[205 rows x 3 columns]

In [14]:
# Numerical $ Categorical columns
cat_col = df.select_dtypes(include='object').columns
num_col = df.select_dtypes(exclude='object').columns

In [15]:
cat_col

Index(['CarName', 'fueltype', 'aspiration', 'doornumber', 'carbody',
       'drivewheel', 'enginelocation'],
      dtype='object')

In [16]:
num_col

Index(['car_ID', 'symboling', 'wheelbase'], dtype='object')

In [17]:
#Assignment
# loc & iloc
# conditional selection of the entries
# how to handle the missing or null values

In [18]:
import numpy as np
import pandas as pd
data = pd.DataFrame({
    'Age' : [20,np.nan,24,25],
    'Height' : [np.nan,180,175,166],
    'Name' : ['Maan','Aman','Naman','Vikash']
},index=['a','b','c','d'])

# loc

In [19]:
# to select a particular row from the dataframe on the 
# basic of the labels then we must have to use the loc
# df.loc[index]
# end include
data.loc['a':'d']

    Age  Height    Name
a  20.0     NaN    Maan
b   NaN   180.0    Aman
c  24.0   175.0   Naman
d  25.0   166.0  Vikash

# iloc

In [20]:
# iloc is know asw integer based indexing into which 
# we asically select the particular row and columns on the 
# basic of integer based indexing into this the en index exclusive
# syntax => df.iloc[row_slicing,columns_slicing]
data.iloc[0:3,0:2]

    Age  Height
a  20.0     NaN
b   NaN   180.0
c  24.0   175.0

In [21]:
# how to handle the missing values of the data frmae 
# so, first of all we have to check weather the data is having any null values
data.isna().sum()

Age       1
Height    1
Name      0
dtype: int64

there are two mathods for null value handling
1. droping the null values
2. impute the null values

In [22]:
data.dropna()
# if there is very less amount of the null present in the
# dataframe then we can use the dropna but it colud lead to the data loss

    Age  Height    Name
c  24.0   175.0   Naman
d  25.0   166.0  Vikash

In [23]:
# imputing the numerical columns which are having the null values
# it can be imputed by two ways => mean,median
# if the columns having any extreme value(outlier) then you must have to impute the the median
# if the columns is not having any outlier the we must have to fill that with mean

In [24]:
df = pd.read_csv("train2.0.csv")
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [25]:
df.isna().sum()

Id                 0
MSSubClass         0
MSZoning           0
LotFrontage      259
LotArea            0
                ...
MoSold             0
YrSold             0
SaleType           0
SaleCondition      0
SalePrice          0
Length: 81, dtype: int64

In [26]:
df['LotFrontage'].fillna(df['LotFrontage'].mean(),inplace=True)

C:\Users\rahul\AppData\Local\Temp\ipykernel_20656\3638690707.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['LotFrontage'].fillna(df['LotFrontage'].mean(),inplace=True)

In [27]:
df['LotFrontage'].isna().sum()

0

In [28]:
# categorical columns
df['Alley'].isna().sum()

1369

In [29]:
df.drop('Alley',axis=1,inplace=True)

In [30]:
cat = df.select_dtypes(include='object').columns
cat

Index(['MSZoning', 'Street', 'LotShape', 'LandContour', 'Utilities',
       'LotConfig', 'LandSlope', 'Neighborhood', 'Condition1', 'Condition2',
       'BldgType', 'HouseStyle', 'RoofStyle', 'RoofMatl', 'Exterior1st',
       'Exterior2nd', 'MasVnrType', 'ExterQual', 'ExterCond', 'Foundation',
       'BsmtQual', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'Heating', 'HeatingQC', 'CentralAir', 'Electrical', 'KitchenQual',
       'Functional', 'FireplaceQu', 'GarageType', 'GarageFinish', 'GarageQual',
       'GarageCond', 'PavedDrive', 'PoolQC', 'Fence', 'MiscFeature',
       'SaleType', 'SaleCondition'],
      dtype='object')

In [31]:
df['MSZoning'].mode()

0    RL
Name: MSZoning, dtype: object

In [32]:
df

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,Reg,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [33]:
df['LotArea'].unique()

array([ 8450,  9600, 11250, ..., 17217, 13175,  9717], dtype=int64)

In [34]:
df[df['LotArea']>10000]

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,LotShape,LandContour,Utilities,LotConfig,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
2,3,60,RL,68.000000,11250,Pave,IR1,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
4,5,60,RL,84.000000,14260,Pave,IR1,Lvl,AllPub,FR2,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
5,6,50,RL,85.000000,14115,Pave,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,Shed,700,10,2009,WD,Normal,143000
6,7,20,RL,75.000000,10084,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,307000
7,8,60,RL,70.049958,10382,Pave,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Shed,350,11,2009,WD,Normal,200000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1442,1443,60,FV,85.000000,11003,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,4,2009,WD,Normal,310000
1446,1447,20,RL,70.049958,26142,Pave,IR1,Lvl,AllPub,CulDSac,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,157900
1448,1449,50,RL,70.000000,11767,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,GdWo,NaN,0,5,2007,WD,Normal,112000
1453,1454,20,RL,90.000000,17217,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,NaN,NaN,0,7,2006,WD,Abnorml,84500
1456,1457,20,RL,85.000000,13175,Pave,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000

In [37]:
# columns in the list
col = df.columns.to_list()
col

['Id',
 'MSSubClass',
 'MSZoning',
 'LotFrontage',
 'LotArea',
 'Street',
 'LotShape',
 'LandContour',
 'Utilities',
 'LotConfig',
 'LandSlope',
 'Neighborhood',
 'Condition1',
 'Condition2',
 'BldgType',
 'HouseStyle',
 'OverallQual',
 'OverallCond',
 'YearBuilt',
 'YearRemodAdd',
 'RoofStyle',
 'RoofMatl',
 'Exterior1st',
 'Exterior2nd',
 'MasVnrType',
 'MasVnrArea',
 'ExterQual',
 'ExterCond',
 'Foundation',
 'BsmtQual',
 'BsmtCond',
 'BsmtExposure',
 'BsmtFinType1',
 'BsmtFinSF1',
 'BsmtFinType2',
 'BsmtFinSF2',
 'BsmtUnfSF',
 'TotalBsmtSF',
 'Heating',
 'HeatingQC',
 'CentralAir',
 'Electrical',
 '1stFlrSF',
 '2ndFlrSF',
 'LowQualFinSF',
 'GrLivArea',
 'BsmtFullBath',
 'BsmtHalfBath',
 'FullBath',
 'HalfBath',
 'BedroomAbvGr',
 'KitchenAbvGr',
 'KitchenQual',
 'TotRmsAbvGrd',
 'Functional',
 'Fireplaces',
 'FireplaceQu',
 'GarageType',
 'GarageYrBlt',
 'GarageFinish',
 'GarageCars',
 'GarageArea',
 'GarageQual',
 'GarageCond',
 'PavedDrive',
 'WoodDeckSF',
 'OpenPorchSF',
 'EnclosedPorch',
 '3SsnPorch',
 'ScreenPorch',
 'PoolArea',
 'PoolQC',
 'Fence',
 'MiscFeature',
 'MiscVal',
 'MoSold',
 'YrSold',
 'SaleType',
 'SaleCondition',
 'SalePrice']

# Handle dupliate values

In [ ]:
data = pd.DataFrame({
    'col1' : [20,30,35,40,40,],
    'col2' : [35,40,45,40,40]
})

In [39]:
data.drop_duplicates(inplace=True)

In [40]:
data

   col1  col2
0    20    35
1    30    40
2    35    45
3    40    40

# Add a new col

In [41]:
data['col3'] = 10
data

   col1  col2  col3
0    20    35    10
1    30    40    10
2    35    45    10
3    40    40    10

In [42]:
data['col4'] = data['col1'] + data['col2']
data

   col1  col2  col3  col4
0    20    35    10    55
1    30    40    10    70
2    35    45    10    80
3    40    40    10    80

# Drop a columns

In [52]:
data.drop('col4',axis=1)

   col1  col2  col3
0    20    35    10
1    30    40    10
2    35    45    10
3    40    40    10

# sort data

In [53]:
data.sort_values(by='col1')

   col1  col2  col3  col4
0    20    35    10    55
1    30    40    10    70
2    35    45    10    80
3    40    40    10    80

   col1  col2  col3  col4
0    20    35    10    55
1    30    40    10    70
2    35    45    10    80
3    40    40    10    80

In [56]:
data = pd.DataFrame({
    'col1' : [20,30,35,40,40,],
    'col2' : [35,40,45,40,40],
    'Name' : ['Aman','Naman','shivam','Satyam','Yash']
})

# string operations

In [58]:
data['Name'].str.capitalize()

0      Aman
1     Naman
2    Shivam
3    Satyam
4      Yash
Name: Name, dtype: object

In [59]:
data['Name'].str.lower()

0      aman
1     naman
2    shivam
3    satyam
4      yash
Name: Name, dtype: object

In [64]:
data = pd.DataFrame({
    'col1' : [20,30,35,40,40,],
    'col2' : [35,40,45,40,40],
    'Full' : ['Aman singh','Naman singh','shivam shrma','Satyam tawri','Yash singh']
})

In [65]:
data['Full'].str.split(' ')

0      [Aman, singh]
1     [Naman, singh]
2    [shivam, shrma]
3    [Satyam, tawri]
4      [Yash, singh]
Name: Full, dtype: object

In [66]:
#06-07-2026

In [68]:
import numpy as np
import pandas as pd

data = pd.DataFrame({
    'dept' : ['IT','SALES','IT','IT','SALES'],
    'salary' : [20000,25000,23000,28000,30000]
})
data

    dept  salary
0     IT   20000
1  SALES   25000
2     IT   23000
3     IT   28000
4  SALES   30000

# Aggregate function

In [69]:
data.groupby('dept')['salary'].max()

dept
IT       28000
SALES    30000
Name: salary, dtype: int64

# Concate

In [70]:
df1 = pd.DataFrame({
    "Emp_id" : [101,102],
    "Name" : ['Vinay','Aman']
})
df2 = pd.DataFrame({
    "Emp_id" : [103,104],
    "Name" : ['Riya','Priya']
})

In [ ]:
# by default axis=0 
vertical = pd.concat([df1,df2])
vertical

   Emp_id   Name
0     101  Vinay
1     102   Aman
0     103   Riya
1     104  Priya

In [73]:
vertical = pd.concat([df1,df2],axis=1)
vertical

   Emp_id   Name  Emp_id   Name
0     101  Vinay     103   Riya
1     102   Aman     104  Priya

In [77]:
employee = pd.DataFrame({
    "Emp_id" : [101,102,103],
    "Name" : ['Vinay','Aman','Riya']
})

salary = pd.DataFrame({
    "Salary" : [50000,45000,60000],
    "Bonus" : [5000,3000,7000]
})

pd.concat([employee,salary],axis=1)

   Emp_id   Name  Salary  Bonus
0     101  Vinay   50000   5000
1     102   Aman   45000   3000
2     103   Riya   60000   7000

# Marge

In [79]:
employee = pd.DataFrame({
    "Emp_id" : [101,102,103,104],
    "Name" : ['Vinay','Aman','Riya','Priya']
})

salary = pd.DataFrame({
    "Emp_id" : [101,102,105],
    "Salary" : [50000,45000,60000]
})

In [86]:
inner = pd.merge(
    employee,
    salary,
    on = "Emp_id",
    how = "right"
)
print(inner)

   Emp_id   Name  Salary
0     101  Vinay   50000
1     102   Aman   45000
2     105    NaN   60000